"""create reviews table

Revision ID: 844eb0010668
Revises: 7fbe2a39fdac
Create Date: 2021-02-02 18:08:20.148946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844eb0010668'
down_revision = '7fbe2a39fdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('restaurant_id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('bags', sa.Boolean(), nullable=True),
                    sa.Column('utensils', sa.Boolean(), nullable=True),
                    sa.Column('napkins', sa.Boolean(), nullable=True),
                    sa.Column('cups', sa.Boolean(), nullable=True),
                    sa.Column('bowls', sa.Boolean(), nullable=True),
                    sa.Column('straws', sa.Boolean(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('updated', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
