"""create cities table

Revision ID: 9bfb5a6b6ae0
Revises: 844eb0010668
Create Date: 2021-02-06 18:14:53.082236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfb5a6b6ae0'
down_revision = '844eb0010668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=40), nullable=False),
                    sa.Column('photo', sa.Text(), nullable=False),
                    sa.Column('lng', sa.String(), nullable=False),
                    sa.Column('lat', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
